<?php

namespace frontend\controllers;

use yii\db\Exception;
use yii\web\Controller;
use Yii;
use common\models\PoetryCategory;
use yii\web\HttpException;

/**
 * PoetryCategory controller for Api
 */
class CategoryController extends Controller
{

    /*
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => \yii\filters\VerbFilter::className(),
                'actions' => [
                    'list'  => ['GET'],
                    'one'   => ['GET'],
                    'create' => ['GET', 'POST'],
                    'update' => ['GET', 'PUT', 'POST'],
                    'delete' => ['POST', 'DELETE'],
                ],
            ],
        ];
    }
    */

    public function beforeAction($action)
    {
        Yii::$app->response->format = 'json';
        Yii::$app->controller->enableCsrfValidation = false;
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionList()
    {
        if(Yii::$app->request->isGet)
            return PoetryCategory::find()->all();
        else throw new HttpException(400);
    }

    public function actionOne($id)
    {
        if(Yii::$app->request->isGet) {
            $category = PoetryCategory::findOne(['id' => $id]);
            if ($category) return $category;
            throw new HttpException(404,'There is no category with this ID');
        } else throw new HttpException(400);
    }

    public function actionCreate()
    {
        if(Yii::$app->request->isPost) {
            try {
                $data = json_decode(file_get_contents("php://input"), true);
                $category = new PoetryCategory;
                $category->setAttributes($data);
                if ($category->save()) {
                    return $category->getAttribute('id');
                }
                $errors_s = '';
                foreach ($category->errors as $error) {
                    if (is_array($error)) {
                        foreach ($error as $err) {
                            $errors_s .= $err.'; ';
                        }
                    }
                }
                throw new HttpException(400, $errors_s);
            } catch (Exception $err) {
                throw new HttpException(400);
            }
        } else throw new HttpException(400);
    }

    public function actionUpdate($id)
    {
        if(Yii::$app->request->isPut) {
            try {
                $category = PoetryCategory::findOne(['id' => $id]);
                if ($category) {
                    $data = json_decode(file_get_contents("php://input"), true);
                    $category->setAttributes($data);
                    if ($category->save()) {
                        return $category;
                    }
                    $errors_s = '';
                    foreach ($category->errors as $error) {
                        if (is_array($error)) {
                            foreach ($error as $err) {
                                $errors_s .= $err.'; ';
                            }
                        }
                    }
                    throw new HttpException(404, $errors_s);
                }
                throw new HttpException(404, 'There is no category with this ID');
            } catch (Exception $err) {
                throw new HttpException(400);
            }
        } else throw new HttpException(400);
    }

    public function actionDelete($id){
        if(Yii::$app->request->isDelete) {
            $category = PoetryCategory::findOne(['id' => $id]);
            if ($category) {
                return $category->delete();
            } else throw new HttpException(404, 'There is no category with this ID');
        } else throw new HttpException(400);
    }
}